menu:
  title: "&a菜 &c单"
  size: 54
  items:
    item0:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 0
    item1:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 1
    item2:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 2
    item3:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 3
    item4:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 4
    item5:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 5
    item6:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 6
    item7:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 7
    item8:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 8
    item9:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 9
    item10:
      material: LEGACY_BEACON
      name: "&a回城"
      command: warp 主城
      lore: "&b&l城市套路深 我要回农村···"
      amount: 1
      slot: 10
    item11:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 11
    item12:
      material: GRASS_BLOCK
      name: "&1生存区"
      command: warp sur
      lore: "&5&l前往生存区 （允许圈地/死亡不掉落） "
      amount: 1
      slot: 12
    item13:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 13
    item14:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 14
    item15:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 15
    item16:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 16
    item17:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 17
    item18:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 18
    item19:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 19
    item20:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 20
    item21:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 21
    item22:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 22
    item23:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 23
    item24:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 24
    item25:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 25
    item26:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 26
    item27:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 27
    item28:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 28
    item29:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 29
    item30:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 30
    item31:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 31
    item32:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 32
    item33:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 33
    item34:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 34
    item35:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 35
    item36:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 36
    item37:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 37
    item38:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 38
    item39:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 39
    item40:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 40
    item41:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 41
    item42:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 42
    item43:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 43
    item44:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 44
    item45:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 45
    item46:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 46
    item47:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 47
    item48:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 48
    item49:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 49
    item50:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 50
    item51:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 51
    item52:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 52
    item53:
      material: BLACK_STAINED_GLASS_PANE
      name: "什么都没有..."
      command: afk
      lore: " "
      amount: 1
      slot: 53
