name: FastMenu
version: '1.0-YiQingYu'
main: org.YQY.fastMenu.FastMenu
api-version: '1.21'
author: YQingYuQWQ
description: FastMenu a simple plugin that allows you to open a menu with a command.
commands:
  cd:
    description: open menu
    usage: /cd
  fm:
    description: reload fast menu.
    usage: /fm reload
permissions:
  fastmenu.reload:
    description: Allows the player to reload the menu
    default: op
